version: "3.9"

services:
  scrp:
    build:
      context: .
      dockerfile: Dockerfile.ubuntu
    command: npm run start-with-hot-reload
    ports:
      - ${APP_PORT}:3000
    volumes:
      - .:/scrp
      - /scrp/node_modules
      - ./public/DataDownload:/scrp/public/DataDownload
    environment:
      MODULES: ${MODULES}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      DB_DATABASE_OVMRD: ovmrd        # ✅ Added for OvarianMRD module
      DB_CONN_LIMIT: ${DB_CONN_LIMIT}
      DB_HOST_TCM: ${DB_HOST_TCM}
      DB_PORT_TCM: ${DB_PORT_TCM}
      DB_USER_TCM: ${DB_USER_TCM}
      DB_PASSWORD_TCM: ${DB_PASSWORD_TCM}
      DB_DATABASE_TCM: ${DB_DATABASE_TCM}
      SSL_KEY: ${SSL_KEY}
      SSL_CA: ${SSL_CERT}
      SSL_CERT: ${SSL_CA}
      SSL_PASSPHRASE: ${SSL_PASSPHRASE}

  db:
    image: mariadb:latest
    container_name: scrp-mariadb
    restart: unless-stopped
    ports:
      - 3307:3306
    volumes:
      - ./data/TCM_custom_export:/data/TCM_custom_export
      - ./data/db:/var/lib/mysql:Z
      - ./seed.sql:/docker-entrypoint-initdb.d/seed.sql
    environment:
      MARIADB_DATABASE: tcm
      MARIADB_ROOT_PASSWORD: test

