services:
  scrp:
    image: ghcr.io/break-through-cancer/rescrp:latest
    command: npm run start-with-hot-reload
    ports:
      - ${APP_PORT:-3000}:3000
    volumes:
      - ./public/DataDownload:/scrp/public/DataDownload
    env_file:
      - .env

  db:
    image: mariadb:latest
    container_name: scrp-mariadb
    restart: unless-stopped
    ports:
      - 3307:3306
    volumes:
      - ./data/TCM_custom_export:/data/TCM_custom_export
      - ./data/db:/var/lib/mysql:Z
      - ./seed.sql:/docker-entrypoint-initdb.d/seed.sql
    environment:
      MARIADB_DATABASE: tcm
      MARIADB_ROOT_PASSWORD: test
