LOAD DATA LOCAL INFILE "/data/TCM/CD4_meta_2025-06-09.tsv" 
INTO TABLE CD4_meta
FIELDS TERMINATED BY '\t'
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(@var1, @var2, @var3)
SET
    Barcode = @var1,
    UMAP1 = @var2,
    UMAP2 = @var3
;

LOAD DATA LOCAL INFILE "/data/TCM/CD8_meta_2025-06-09.tsv" 
INTO TABLE CD8_meta
FIELDS TERMINATED BY '\t'
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(@var1, @var2, @var3)
SET
    Barcode = @var1,
    UMAP1 = @var2,
    UMAP2 = @var3
;

LOAD DATA LOCAL INFILE "/data/TCM/CD4_EXP_2025-06-09.tsv" 
INTO table CD4_EXP
FIELDS TERMINATED BY '\t'
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

LOAD DATA LOCAL INFILE "/data/TCM/CD8_EXP_2025-06-09.tsv" 
INTO TABLE CD8_EXP
FIELDS TERMINATED BY '\t'
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES;
