-- Load OvMRD data from TSV files

-- ALL Meta Data
LOAD DATA LOCAL INFILE "/data/OvMRD/tsv_output/ALL_meta_2025-10-19.tsv"
INTO TABLE ALL_meta
FIELDS TERMINATED BY '\t'
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

-- BPlasma Meta Data
LOAD DATA LOCAL INFILE "/data/OvMRD/tsv_output/BPlasma_meta_2025-10-19.tsv"
INTO TABLE BPlasma_meta
FIELDS TERMINATED BY '\t'
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

-- CD4T Meta Data
LOAD DATA LOCAL INFILE "/data/OvMRD/tsv_output/CD4T_meta_2025-10-19.tsv"
INTO TABLE CD4T_meta
FIELDS TERMINATED BY '\t'
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

-- CD8T Meta Data
LOAD DATA LOCAL INFILE "/data/OvMRD/tsv_output/CD8T_meta_2025-10-19.tsv"
INTO TABLE CD8T_meta
FIELDS TERMINATED BY '\t'
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

-- Myeloid Meta Data
LOAD DATA LOCAL INFILE "/data/OvMRD/tsv_output/Myeloid_meta_2025-10-19.tsv"
INTO TABLE Myeloid_meta
FIELDS TERMINATED BY '\t'
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

-- NK Meta Data
LOAD DATA LOCAL INFILE "/data/OvMRD/tsv_output/NK_meta_2025-10-19.tsv"
INTO TABLE NK_meta
FIELDS TERMINATED BY '\t'
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

-- TNK Meta Data
LOAD DATA LOCAL INFILE "/data/OvMRD/tsv_output/TNK_meta_2025-10-19.tsv"
INTO TABLE TNK_meta
FIELDS TERMINATED BY '\t'
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

-- BPlasma Expression Data
LOAD DATA LOCAL INFILE "/data/OvMRD/tsv_output/BPlasma_EXP_2025-10-19.tsv"
INTO TABLE BPlasma_EXP
FIELDS TERMINATED BY '\t'
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

-- CD4T Expression Data
LOAD DATA LOCAL INFILE "/data/OvMRD/tsv_output/CD4T_EXP_2025-10-19.tsv"
INTO TABLE CD4T_EXP
FIELDS TERMINATED BY '\t'
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

-- CD8T Expression Data
LOAD DATA LOCAL INFILE "/data/OvMRD/tsv_output/CD8T_EXP_2025-10-19.tsv"
INTO TABLE CD8T_EXP
FIELDS TERMINATED BY '\t'
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

-- Myeloid Expression Data
LOAD DATA LOCAL INFILE "/data/OvMRD/tsv_output/Myeloid_EXP_2025-10-19.tsv"
INTO TABLE Myeloid_EXP
FIELDS TERMINATED BY '\t'
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

-- NK Expression Data
LOAD DATA LOCAL INFILE "/data/OvMRD/tsv_output/NK_EXP_2025-10-19.tsv"
INTO TABLE NK_EXP
FIELDS TERMINATED BY '\t'
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

-- TNK Expression Data
LOAD DATA LOCAL INFILE "/data/OvMRD/tsv_output/TNK_EXP_2025-10-19.tsv"
INTO TABLE TNK_EXP
FIELDS TERMINATED BY '\t'
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

-- BPlasma DEG Data
LOAD DATA LOCAL INFILE "/data/OvMRD/tsv_output/BPlasma_DEGs_2025-10-19.tsv"
INTO TABLE BPlasma_DEG
FIELDS TERMINATED BY '\t'
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

-- CD4T DEG Data
LOAD DATA LOCAL INFILE "/data/OvMRD/tsv_output/CD4T_DEGs_2025-10-19.tsv"
INTO TABLE CD4T_DEG
FIELDS TERMINATED BY '\t'
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

-- CD8T DEG Data
LOAD DATA LOCAL INFILE "/data/OvMRD/tsv_output/CD8T_DEGs_2025-10-19.tsv"
INTO TABLE CD8T_DEG
FIELDS TERMINATED BY '\t'
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

-- Myeloid DEG Data
LOAD DATA LOCAL INFILE "/data/OvMRD/tsv_output/Myeloid_DEGs_2025-10-19.tsv"
INTO TABLE Myeloid_DEG
FIELDS TERMINATED BY '\t'
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

-- NK DEG Data
LOAD DATA LOCAL INFILE "/data/OvMRD/tsv_output/NK_DEGs_2025-10-19.tsv"
INTO TABLE NK_DEG
FIELDS TERMINATED BY '\t'
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

-- TNK DEG Data
LOAD DATA LOCAL INFILE "/data/OvMRD/tsv_output/TNK_DEGs_2025-10-19.tsv"
INTO TABLE TNK_DEG
FIELDS TERMINATED BY '\t'
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES;
